// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARSUGTFpVCdZDOAgc60gUbVXOG_vMjm9U',
    appId: '1:1034510147658:web:47ac918a7dadaa534306b3',
    messagingSenderId: '1034510147658',
    projectId: 'flutter-notifications-6713f',
    authDomain: 'flutter-notifications-6713f.firebaseapp.com',
    storageBucket: 'flutter-notifications-6713f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1VgB6OaLJbNqS_jyva5jdPvdH7ziG3c4',
    appId: '1:1034510147658:android:d9598a07c36102f14306b3',
    messagingSenderId: '1034510147658',
    projectId: 'flutter-notifications-6713f',
    storageBucket: 'flutter-notifications-6713f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9lweYP1fykP8UOiaAYPTUQ-A8nfWVQMM',
    appId: '1:1034510147658:ios:c89645c34412ebb84306b3',
    messagingSenderId: '1034510147658',
    projectId: 'flutter-notifications-6713f',
    storageBucket: 'flutter-notifications-6713f.appspot.com',
    iosClientId: '1034510147658-phaedjjjo6ovtpge94o9q87ng8l8c857.apps.googleusercontent.com',
    iosBundleId: 'com.example.pushApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9lweYP1fykP8UOiaAYPTUQ-A8nfWVQMM',
    appId: '1:1034510147658:ios:66a62fd9d0accca04306b3',
    messagingSenderId: '1034510147658',
    projectId: 'flutter-notifications-6713f',
    storageBucket: 'flutter-notifications-6713f.appspot.com',
    iosClientId: '1034510147658-tet67iu0t2k2lrk1psai8u8lhb2q45uu.apps.googleusercontent.com',
    iosBundleId: 'com.example.pushApp.RunnerTests',
  );
}
